name: cleaning_report_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  google_fonts: ^6.3.0
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  supabase_flutter: ^2.3.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.4

flutter:
  uses-material-design: true
